config/routes.rb
DaBlog::Application.routes.draw do

  get "sessions/new"

  resources :blogposts
  resources :categories
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/signup', :to => 'users#new'
  match '/tags/:categories', :to => 'blogposts#tags'
  match '/blogposts', :to => 'blogposts#index'
  match '/categories', :to => 'categories#index'


  root :to => 'pages#home'

  get "pages/home"
  get "pages/contact"
  get "pages/about"


end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
    attr_accessible :content, :title, :category, :published, :category_ids

    belongs_to :user
    has_and_belongs_to_many :categories

    validates :content, :presence => true
    validates :title, :presence => true, :length => { :maximum => 140 }
    validates_inclusion_of :published, :in => [true,false]
    validates :user_id, :presence => true

    default_scope :order => 'blogposts.created_at DESC'


end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController

  before_filter :authenticate
  before_filter :admin_user, :only => [:index, :edit, :update, :destroy]

  # GET /blogposts
  def index
    @blogposts = Blogpost.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @blogposts }
    end
  end


  # GET /blogposts/1
  def show
    @blogpost = Blogpost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @blogpost }
    end
  end


  # GET /blogposts/new
  def new
    @blogpost = Blogpost.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @blogpost }
    end
  end


  # GET /blogposts/1/edit
  def edit
    @blogpost = Blogpost.find(params[:id])
  end


  # POST /blogposts
  def create
    @blogpost = current_user.blogposts.build(params[:blogpost])

    respond_to do |format|
      if @blogpost.save
        format.html { redirect_to(@blogpost, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @blogpost, :status => :created, :location => @blogpost }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @blogpost.errors, :status => :unprocessable_entity }
      end
    end
  end


  # PUT /blogposts/1
  def update

    params[:blogpost][:category_ids] ||= []

    @blogpost = Blogpost.find(params[:id])

    respond_to do |format|
      if @blogpost.update_attributes(params[:blogpost])
        format.html { redirect_to(@blogpost, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @blogpost.errors, :status => :unprocessable_entity }
      end
    end
  end


  # DELETE /blogposts/1
  def destroy
    @blogpost = Blogpost.find(params[:id])
    @blogpost.destroy

    respond_to do |format|
      format.html { redirect_to(blogposts_url) }
      format.xml  { head :ok }
    end
  end

  private

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

end

app/helpers/blogposts_helper.rb
module BlogpostsHelper

  def blogpost_belongs_category?(category)
    if @blogpost  # no sense in testing new users that have no languages
        @blogpost.categories.include?(category)
    else
        false
    end
  end

end

app/views/blogposts/_blogpost.erb
<tr>
  <td class="blogpost">
    <div class="blog_title"><%= blogpost.title %></div>
    <div class="blog_timestamp">Posted <%= time_ago_in_words(blogpost.created_at) %> ago by <%= blogpost.user.login %></div>
    <div class="blog_content"><%= blogpost.content %></div>
  </td>
</tr>

app/views/blogposts/_form.html.erb
<%= form_for(@blogpost) do |f| %>
  <% if @blogpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blogpost.errors.count, "error") %> prohibited this blogpost from being saved:</h2>

      <ul>
      <% @blogpost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="title_field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="content_area">
    <%= f.label :content %><br />
    <%= f.text_area :content, :rows => 6 %>
  </div>

  <div class="category_field">
    <%= f.label :Category %><br />


    <% Category.find(:all).each do |category| %>
        <p>
            <%= check_box_tag "blogpost[category_ids][]", category.id, blogpost_belongs_category?(category) -%> <%= category.name -%>
        </p>
    <% end %>


  </div>

  <div class="publish_checkbox">
    <%= f.label :published %><br />
    <%= f.check_box :published %>
  </div>
  <div class="blogpost_actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogposts/edit.html.erb
<div class="title">
<h1>EDIT POST</h1>
</div>


<div class="page">

<%= render 'form' %>

<%= link_to 'Show', @blogpost %> |
<%= link_to 'Back', blogposts_path %>

</div>

app/views/blogposts/index.html.erb
<div class="title">
<h1>BLOGPOSTS</h1>
</div>

<div class="page">
<table>
  <tr>
    <th>Title</th>
    <th>Category</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogposts.each do |blogpost| %>
  <tr>
    <td><%= blogpost.title %></td>
    <td>
        <% blogpost.categories.each do |category| %> <%= category.name %>  <% end %>
    </td>
    <td><%= blogpost.user.login %></td>
    <td><%= link_to 'Show', blogpost %> |</td>
    <td> <%= link_to 'Edit', edit_blogpost_path(blogpost) %> |</td>
    <td> <%= link_to 'Destroy', blogpost, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blogpost', new_blogpost_path %>

</div>

app/views/blogposts/new.html.erb
<div class="title">
<h1>NEW POST</h1>
</div>

<div class="page">

<%= render 'form' %>

<%= link_to 'Back', blogposts_path %>

</div>

app/views/blogposts/show.html.erb
<div class="title">
    <h1><%= @blogpost.title %></h1>
</div>


<div class="page">

<p>
  <b>Title:</b>
  <%= @blogpost.title %>
</p>

<p>
  <b>Content:</b>
  <%= @blogpost.content %>
</p>

<p>
  <b>Category:</b>
  <%= @blogpost.category %>
</p>

<p>
  <b>User:</b>
  <%= @blogpost.user_id %>
</p>

<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_blogpost_path(@blogpost) %> |
<%= link_to 'Back', blogposts_path %>

</div>

app/views/blogposts/tags.html.erb
<div class="title">
<h1>WELCOME TO DA BLOG</h1>
</div>


<div class="page">

  <div class="blogframe">

<table class="blogposts" summary="User blogposts">
          <%= render @blogposts %>
</table>

<%= will_paginate @blogposts %>

  </div>

</div>