config/routes.rb
DaBlog::Application.routes.draw do

  get "sessions/new"

  resources :blogposts
  resources :categories
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/signup', :to => 'users#new'
  match '/tags/:categories', :to => 'blogposts#tags'
  match '/blogposts', :to => 'blogposts#index'
  match '/categories', :to => 'categories#index'


  root :to => 'pages#home'

  get "pages/home"
  get "pages/contact"
  get "pages/about"


end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>

    <nav class="round">
		<ul>
			    <li><%= link_to "HOME", root_path %></li>
			<% if signed_in? %>
			    <li><%= link_to "USERS", users_path %></li>
			    <li><%= link_to "PROFILE", current_user %></li>
            <% end %>
            <% if is_admin? %>
			    <li><%= link_to "BLOGPOSTS", blogposts_path %></li>
			<% end %>
			    <li><%= link_to "ABOUT", about_path %></li>
			<% if signed_in? %>
			    <li><%= link_to "SIGN OUT", signout_path, :method => :delete %></li>
			<% else %>
			    <li><%= link_to "SIGN IN", signin_path %></li>
			<% end %>    </ul>
		</nav>
	</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
	
	   	<div class="container">
		      <%= render 'layouts/header' %>
			      <section class="round">

				        <%= yield %>

                        <% flash.each do |key, value| %>
				          <div class="flash <%= key %>"><%= value %></div>
				        <% end %>

				      </section>
		   <!--   <%= render 'layouts/footer' %>  -->
		      <%= debug(params) if Rails.env.development? %>
		</div>
  </body>
</html>